import { useEffect, useMemo, useRef, useState } from 'react';
import Editor from '@monaco-editor/react';
import { ArrowLeft, Bot, Braces, CheckCircle2, ChevronRight, CircleStop, Code2, Cog, Eye, EyeOff, File, FileCode2, FileText, Folder, FolderOpen, Github, History, Image, Info, Instagram, KeyRound, Maximize2, Minus, Palette, PanelLeft, Play, Plus, Save, Send, Settings2, ShieldAlert, Terminal, Trash2, X } from 'lucide-react';
import type { AgentEvent, AuditEntry, ChatHistoryItem, ChatSession, FileNode, ModelInfo, Provider, Settings, ToolRequest } from '../shared/types';
import helixLogo from '../../logo.png';

type Chat = { role: 'user' | 'assistant' | 'reasoning' | 'tool' | 'error' | 'system'; text: string; id: string };
type FileChange = { path: string; action: 'created' | 'modified' | 'deleted'; preview: string };
type ExplorerMenu = { x: number; y: number; items: FileNode[]; scope: 'node' | 'root' | 'empty' };
type CreateRequest = { directory: boolean; parent: string };
const newChatSession = (): ChatSession => { const now = new Date().toISOString(); return { id: crypto.randomUUID(), title: 'New chat', createdAt: now, updatedAt: now, messages: [] }; };
const basename = (p: string) => p.split(/[\\/]/).filter(Boolean).pop() ?? p;
const parentDirectory = (p: string) => p.replace(/[\\/][^\\/]+$/, '');
function webSearchReason(message: string) { const continueWithoutWeb = /\bcontinue (without web|with the latest information i have)|no (web|external assets?|urls?)\b/i.test(message); if (continueWithoutWeb) return null; const currentInfo = /\b(search (the )?web|web search|latest|current (news|version|price|information|docs?|documentation)|today(?:'s)?|recent|up[- ]to[- ]date|right now|trending (now|today)|number\s*1|#\s*1|from (the )?(web|internet)|find online)\b/i.test(message); if (currentInfo) return 'current web information'; const externalUrlOrAsset = /\b(urls?|links?|external (assets?|images?|urls?)|background (image|url)|hero (image|background)|actual (images?|posters?|photos?)|movie posters?|stock (images?|photos?)|image urls?|web fonts?|google fonts?|favicon|embeds?|youtube|maps?|api (data|integration|endpoint)|live (data|feed)|cdn)\b/i.test(message); return externalUrlOrAsset ? 'external URLs or online assets' : null; }
const onboardingProviders: { provider: Provider; label: string; free?: boolean }[] = [{ provider: 'openrouter', label: 'OpenRouter', free: true }, { provider: 'gemini', label: 'Gemini', free: true }, { provider: 'groq', label: 'Groq' }, { provider: 'ollama', label: 'Ollama', free: true }, { provider: 'lmstudio', label: 'LM Studio', free: true }, { provider: 'openai', label: 'OpenAI' }, { provider: 'anthropic', label: 'Anthropic' }, { provider: 'compatible', label: 'Custom API' }];
function language(path: string) { const ext = path.split('.').pop()?.toLowerCase(); return ({ ts:'typescript', tsx:'typescript', js:'javascript', jsx:'javascript', json:'json', css:'css', html:'html', md:'markdown', py:'python', yml:'yaml', yaml:'yaml', sh:'shell', ps1:'powershell' } as Record<string,string>)[ext ?? ''] ?? 'plaintext'; }
function toolActivity(request: ToolRequest, complete = false) { const path = typeof request.args.path === 'string' ? basename(request.args.path) : ''; const action: Record<string,string> = { list_dir:'Listing', read_file:'Reading', write_file:'Writing', edit_file:'Editing', delete_file:'Deleting', create_directory:'Creating folder', search_in_files:'Searching', run_command:'Running command' }; return `${complete ? 'Done · ' : ''}${action[request.tool] ?? request.tool}${path ? ` · ${path}` : ''}`; }

export function App() {
  const [root, setRoot] = useState<string | null>(null), [nodes, setNodes] = useState<FileNode[]>([]), [open, setOpen] = useState<{ path: string; content: string; dirty?: boolean }[]>([]), [active, setActive] = useState<string | null>(null);
  const [settings, setSettings] = useState<Settings | null>(null), [showSettings, setShowSettings] = useState(false), [showOnboarding, setShowOnboarding] = useState(false), [tab, setTab] = useState<'chat'|'history'>('chat');
  const [chat, setChat] = useState<Chat[]>([]), [draft, setDraft] = useState(''), [running, setRunning] = useState(false), [approval, setApproval] = useState<ToolRequest | null>(null), [audit, setAudit] = useState<AuditEntry[]>([]), [fileChanges, setFileChanges] = useState<FileChange[]>([]), [chatModels, setChatModels] = useState<ModelInfo[]>([]), [sessions, setSessions] = useState<ChatSession[]>([]), [activeSession, setActiveSession] = useState(''), [activeTool, setActiveTool] = useState<string | null>(null), [deleteSessionId, setDeleteSessionId] = useState<string | null>(null); const stickToChatEnd = useRef(true), chatHistoryReady = useRef(false);
  const [explorerSelection, setExplorerSelection] = useState<FileNode[]>([]), [selectionAnchor, setSelectionAnchor] = useState<string | null>(null), [explorerMenu, setExplorerMenu] = useState<ExplorerMenu | null>(null), [pendingExplorerDelete, setPendingExplorerDelete] = useState<FileNode[] | null>(null), [pendingCreate, setPendingCreate] = useState<CreateRequest | null>(null), [treeRevision, setTreeRevision] = useState(0), [explorerWidth, setExplorerWidth] = useState(250), [agentWidth, setAgentWidth] = useState(400), [resizing, setResizing] = useState<'explorer'|'agent'|null>(null);
  const current = open.find(f => f.path === active);
  const refresh = async () => { setNodes(await window.helix.getTree()); setTreeRevision(version => version + 1); };
  const uniqueExplorerItems = (items: FileNode[]) => [...new Map(items.map(item => [item.path, item])).values()];
  function selectExplorerItem(item: FileNode, additive: boolean) { setExplorerMenu(null); setExplorerSelection(old => additive ? old.some(selected => selected.path === item.path) ? old.filter(selected => selected.path !== item.path) : [...old, item] : [item]); if (!additive) setSelectionAnchor(item.path); }
  function selectExplorerRange(siblings: FileNode[], item: FileNode) { setExplorerMenu(null); const anchorIndex = siblings.findIndex(sibling => sibling.path === selectionAnchor); const itemIndex = siblings.findIndex(sibling => sibling.path === item.path); if (anchorIndex < 0 || itemIndex < 0) { setExplorerSelection([item]); setSelectionAnchor(item.path); return; } setExplorerSelection(siblings.slice(Math.min(anchorIndex, itemIndex), Math.max(anchorIndex, itemIndex) + 1)); }
  function showExplorerMenu(item: FileNode, x: number, y: number) { const items = explorerSelection.some(selected => selected.path === item.path) ? explorerSelection : [item]; if (!explorerSelection.some(selected => selected.path === item.path)) { setExplorerSelection([item]); setSelectionAnchor(item.path); } setExplorerMenu({ x, y, items, scope: 'node' }); }
  function showExplorerMenuAt(x: number, y: number) { setExplorerMenu({ x, y, items: explorerSelection, scope: 'empty' }); }
  function showExplorerRootMenu(x: number, y: number) { setExplorerMenu({ x, y, items: [], scope: 'root' }); }
  async function selectAllExplorer() { const selected: FileNode[] = []; const visit = async (items: FileNode[]) => { for (const item of items) { selected.push(item); if (item.type === 'directory') await visit(await window.helix.getTree(item.path)); } }; await visit(nodes); setExplorerSelection(uniqueExplorerItems(selected)); setSelectionAnchor(selected[0]?.path ?? null); setExplorerMenu(null); }
  const topLevelDeleteItems = (items: FileNode[]) => uniqueExplorerItems(items).filter(item => !items.some(parent => parent.path !== item.path && (item.path.startsWith(`${parent.path}\\`) || item.path.startsWith(`${parent.path}/`))));
  async function confirmExplorerDelete() { const items = pendingExplorerDelete ? topLevelDeleteItems(pendingExplorerDelete) : []; setPendingExplorerDelete(null); try { for (const item of items) await window.helix.deletePath(item.path); setOpen(old => old.filter(file => !items.some(item => file.path === item.path || file.path.startsWith(`${item.path}\\`) || file.path.startsWith(`${item.path}/`)))); setActive(old => old && items.some(item => old === item.path || old.startsWith(`${item.path}\\`) || old.startsWith(`${item.path}/`)) ? null : old); setExplorerSelection([]); setSelectionAnchor(null); await refresh(); } catch (error: any) { alert(error.message || String(error)); await refresh(); } }
  useEffect(() => { const pane = document.querySelector<HTMLDivElement>('.messages'); if (!pane) return; const onScroll = () => { stickToChatEnd.current = pane.scrollHeight - pane.scrollTop - pane.clientHeight < 24; }; onScroll(); pane.addEventListener('scroll', onScroll); return () => pane.removeEventListener('scroll', onScroll); }, []);
  useEffect(() => { const pane = document.querySelector<HTMLDivElement>('.messages'); if (pane && stickToChatEnd.current) pane.scrollTo({ top: pane.scrollHeight, behavior: 'smooth' }); }, [chat, running]);
  useEffect(() => { document.querySelector<HTMLTextAreaElement>('.composer textarea')?.removeAttribute('disabled'); });
  useEffect(() => { if (!explorerMenu) return; const close = () => setExplorerMenu(null); window.addEventListener('pointerdown', close); return () => window.removeEventListener('pointerdown', close); }, [explorerMenu]);
  useEffect(() => { window.helix.getChatHistory().then(history => { const initial = history.length ? history : [newChatSession()]; setSessions(initial); setActiveSession(initial[0].id); setChat(initial[0].messages); chatHistoryReady.current = true; }).catch(() => { const initial=[newChatSession()];setSessions(initial);setActiveSession(initial[0].id);chatHistoryReady.current=true; }); }, []);
  useEffect(() => { if (!chatHistoryReady.current || !activeSession) return; setSessions(old => { const next = old.map(session => session.id === activeSession ? { ...session, title: chat.find(message => message.role === 'user')?.text.slice(0, 52) || session.title, updatedAt: new Date().toISOString(), messages: chat as ChatHistoryItem[] } : session); void window.helix.saveChatHistory(next); return next; }); }, [chat, activeSession]);
  useEffect(() => { if (!settings) return; const local = settings.provider === 'ollama' || settings.provider === 'lmstudio'; if (!local && !settings.apiKey) { setChatModels([]); return; } window.helix.listModels(settings).then(setChatModels).catch(() => setChatModels([])); }, [settings?.provider, settings?.apiKey, settings?.baseUrl]);
  useEffect(() => { window.helix.getWorkspaceRoot().then(async remembered => { if (!remembered) return; try { setRoot(remembered); setNodes(await window.helix.getTree()); } catch { setRoot(null); } }); }, []);
  useEffect(() => { window.helix.getSettings().then(s => { setSettings(s); setShowOnboarding(!s.onboardingComplete); if (s.permissionMode === 'extended') {} }); window.helix.getAudit().then(setAudit); const unsubscribe = window.helix.onAgentEvent(onAgent); return unsubscribe; }, []);
  function onAgentLegacy(event: AgentEvent) {
    if (event.type === 'text' && event.content) setChat(old => { const last = old.at(-1); return last?.role === 'assistant' ? [...old.slice(0,-1), { ...last, text: last.text + event.content }] : [...old, { id: crypto.randomUUID(), role: 'assistant', text: event.content! }]; });
    if (event.type === 'tool' && event.request) { setChat(old => [...old, { id: crypto.randomUUID(), role: 'tool', text: `${event.request!.tool} · ${JSON.stringify(event.request!.args)}` }]); if (needsApproval(event.request)) setApproval(event.request); }
    if (event.type === 'tool-result') { refresh(); window.helix.getAudit().then(setAudit); if (event.request && event.result) { setChat(old => [...old, { id: crypto.randomUUID(), role: event.result!.error ? 'error' : 'tool', text: `${event.request!.tool}: ${event.result!.content}` }]); const args:any=event.request.args; if (!event.result.error && ['write_file','edit_file','delete_file'].includes(event.request.tool) && args.path) { const action:FileChange['action']=event.request.tool==='delete_file'?'deleted':event.request.tool==='edit_file'||event.result.content.toLowerCase().includes('modified')?'modified':'created'; const preview=String(args.content ?? args.patch ?? ''); setFileChanges(old=>[...old.filter(change=>change.path!==args.path),{path:args.path,action,preview}]); } } }
    if (event.type === 'done' || event.type === 'error') { setRunning(false); if (event.type === 'error') setChat(old => [...old, { id: crypto.randomUUID(), role: 'error', text: event.content ?? 'Agent stopped.' }]); }
  }
  function onAgent(event: AgentEvent) {
    if (event.type === 'text' && event.content) setChat(old => { const last = old.at(-1); const text = last?.role === 'assistant' ? last.text + event.content : event.content!; if (/^\s*\{[\s\S]*"(name|arguments)"\s*:/m.test(text)) return last?.role === 'assistant' ? old.slice(0, -1) : old; return last?.role === 'assistant' ? [...old.slice(0, -1), { ...last, text }] : [...old, { id: crypto.randomUUID(), role: 'assistant', text }]; });
    if (event.type === 'reasoning' && event.content) setChat(old => { const last = old.at(-1); return last?.role === 'reasoning' ? [...old.slice(0, -1), { ...last, text: last.text + event.content }] : [...old, { id: crypto.randomUUID(), role: 'reasoning', text: event.content! }]; });
    if (event.type === 'tool' && event.request) { setActiveTool(toolActivity(event.request)); if (needsApproval(event.request)) setApproval(event.request); }
    if (event.type === 'tool-result') { setActiveTool(null); refresh(); window.helix.getAudit().then(setAudit); if (event.request && event.result) { const args: any = event.request.args; if (event.result.error) setChat(old => [...old, { id: crypto.randomUUID(), role: 'error', text: `${toolActivity(event.request!)} failed: ${event.result!.content.slice(0, 180)}` }]); if (!event.result.error && ['write_file', 'edit_file', 'delete_file'].includes(event.request.tool) && args.path) { const action: FileChange['action'] = event.request.tool === 'delete_file' ? 'deleted' : event.request.tool === 'edit_file' || event.result.content.toLowerCase().includes('modified') ? 'modified' : 'created'; setFileChanges(old => [...old.filter(change => change.path !== args.path), { path: args.path, action, preview: String(args.content ?? args.patch ?? '') }]); } } }
    if (event.type === 'done' || event.type === 'error') { setRunning(false); setActiveTool(null); if (event.type === 'error') setChat(old => [...old, { id: crypto.randomUUID(), role: 'error', text: event.content ?? 'Agent stopped.' }]); }
  }
  const needsApproval = (r: ToolRequest) => r.reason === 'approval-required';
  async function pickFolder() { const picked = await window.helix.chooseFolder(); if (picked) { setRoot(picked); setOpen([]); setActive(null); await refresh(); } }
  async function closeFolder() { await window.helix.closeWorkspace(); setRoot(null); setNodes([]); setOpen([]); setActive(null); setExplorerSelection([]); setSelectionAnchor(null); setExplorerMenu(null); }
  function startResize(side: 'explorer' | 'agent', event: React.PointerEvent<HTMLDivElement>) { event.preventDefault(); const startX = event.clientX; const startWidth = side === 'explorer' ? explorerWidth : agentWidth; setResizing(side); const move = (next: PointerEvent) => { const delta = side === 'explorer' ? next.clientX - startX : startX - next.clientX; const width = Math.max(side === 'explorer' ? 190 : 320, Math.min(side === 'explorer' ? 430 : 560, startWidth + delta)); side === 'explorer' ? setExplorerWidth(width) : setAgentWidth(width); }; const stop = () => { setResizing(null); document.removeEventListener('pointermove', move); document.removeEventListener('pointerup', stop); }; document.addEventListener('pointermove', move); document.addEventListener('pointerup', stop, { once: true }); }
  async function openFile(path: string) { const exists = open.find(x => x.path === path); if (exists) return setActive(path); try { const content = await window.helix.readFile(path); setOpen(old => [...old, { path, content }]); setActive(path); } catch (e: any) { alert(e.message); } }
  async function save() { if (!current) return; await window.helix.writeFile(current.path, current.content); setOpen(old => old.map(f => f.path === current.path ? { ...f, dirty: false } : f)); await refresh(); }
  function requestCreate(directory: boolean, parent = root) { if (parent) setPendingCreate({ directory, parent }); }
  async function create(directory: boolean, parent: string, name: string) { if (!name.trim()) return; try { await window.helix.createPath(`${parent.replace(/[\\/]+$/, '')}\\${name.trim()}`, directory); setPendingCreate(null); await refresh(); } catch (e: any) { alert(e.message); } }
  async function renameExplorerItem(item: FileNode) { const name = prompt(`Rename ${item.type}`, item.name); if (!name?.trim() || name.trim() === item.name) return; const nextPath = `${parentDirectory(item.path)}\\${name.trim()}`; try { await window.helix.renamePath(item.path, nextPath); const remap = (path: string) => path === item.path ? nextPath : path.startsWith(`${item.path}\\`) || path.startsWith(`${item.path}/`) ? `${nextPath}${path.slice(item.path.length)}` : path; setOpen(old => old.map(file => ({ ...file, path: remap(file.path) }))); setActive(old => old ? remap(old) : null); setExplorerSelection([]); await refresh(); } catch (e: any) { alert(e.message); } }
  async function copyExplorerPaths(items: FileNode[]) { if (!items.length) return; const text = items.map(item => item.path).join('\n'); try { await navigator.clipboard.writeText(text); } catch { prompt('Copy path', text); } setExplorerMenu(null); }
  const explorerParent = (items: FileNode[]) => { const item = items[0]; return item ? item.type === 'directory' ? item.path : parentDirectory(item.path) : root; };
  async function remove() { if (!active || !confirm(`Delete ${basename(active)}?`)) return; await window.helix.deletePath(active); setOpen(old => old.filter(f => f.path !== active)); setActive(null); refresh(); }
  async function submit() { const message = draft.trim(); if (!root || !message || running) return; const webReason = webSearchReason(message); if (!settings?.webSearchEnabled && webReason) { setDraft(''); setChat(old => [...old, { id: crypto.randomUUID(), role: 'user', text: message }, { id: crypto.randomUUID(), role: 'assistant', text: `This request may need ${webReason}. I do not currently have web-search access. Turn on Web search beside the model picker, or ask me to continue without web using the latest information I have.` }]); return; } const modelChangeIndex = chat.reduce((last, item, index) => item.role === 'system' && item.text.startsWith('Model changed to ') ? index : last, -1); const priorMessages = chat.slice(modelChangeIndex + 1).filter(item => item.role === 'user' || item.role === 'assistant'); const localModel = settings?.provider === 'ollama' || settings?.provider === 'lmstudio'; const contextMessages = localModel ? priorMessages.filter(item => item.role === 'assistant' || item.text !== message).slice(-4) : priorMessages; const modelContext = contextMessages.map(item => ({ role: item.role as 'user'|'assistant', content: localModel ? item.text.slice(-2500) : item.text })); setDraft(''); setFileChanges([]); setRunning(true); setChat(old => [...old, { id: crypto.randomUUID(), role: 'user', text: message }]); try { await window.helix.startAgent(message, modelContext); } catch (e: any) { setRunning(false); setChat(old => [...old, { id: crypto.randomUUID(), role: 'error', text: e.message }]); } }
  function resolveApproval(ok: boolean, always = false) { if (!approval) return; const request = approval; if (always) (request.args as any).alwaysAllow = true; window.helix.respondTool(request.id, ok ? { content: 'Approved.' } : { content: 'Denied by user.', error: true }); setApproval(null); }
  function recordModelChange(provider: Provider, model: string, label?: string) { if (!model) return; const name = label ?? model; const short = name.length > 36 ? `${name.slice(0, 33)}...` : name; const providerName = ({ openrouter: 'OpenRouter', gemini: 'Gemini', groq: 'Groq', openai: 'OpenAI', anthropic: 'Anthropic', ollama: 'Ollama', lmstudio: 'LM Studio', compatible: 'Custom' } as Record<Provider,string>)[provider]; const text = `Model changed to ${providerName} / ${short}`; setChat(old => { const last = old.at(-1); return last?.role === 'system' && last.text.startsWith('Model changed to ') ? [...old.slice(0, -1), { ...last, text }] : [...old, { id: crypto.randomUUID(), role: 'system', text }]; }); }
  async function saveSettings(next: Settings) { try { const changed = !settings || next.provider !== settings.provider || next.model !== settings.model; await window.helix.saveSettings(next); setSettings(next); if (changed) recordModelChange(next.provider, next.model); setShowSettings(false); } catch (e: any) { alert(e.message); } }
  async function selectChatModel(model: string) { if (!settings || !model || model === settings.model) return; const next = { ...settings, model }; try { await window.helix.saveSettings(next); setSettings(next); recordModelChange(next.provider, model, chatModels.find(item => item.id === model)?.label); } catch (e: any) { alert(e.message); } }
  async function toggleWebSearch() { if (!settings) return; const next = { ...settings, webSearchEnabled: !settings.webSearchEnabled }; try { await window.helix.saveSettings(next); setSettings(next); } catch (e: any) { alert(e.message); } }
  async function completeOnboarding(provider: Provider, apiKey: string, model: string) { if (!settings) return; const apiKeys = { ...settings.apiKeys, [provider]: apiKey }; const next = { ...settings, onboardingComplete: true, provider, apiKey, apiKeys, baseUrl: providerDefaults[provider].baseUrl, model }; try { await window.helix.saveSettings(next); setSettings(next); setShowOnboarding(false); } catch (e: any) { alert(e.message); } }
  function createNewChat() { const current = sessions.find(session => session.id === activeSession); if (current && current.messages.length === 0 && current.title === 'New chat') { setTab('chat'); return; } const session = newChatSession(); setSessions(old => [session, ...old]); setActiveSession(session.id); setChat([]); setFileChanges([]); setTab('chat'); }
  function openChatSession(session: ChatSession) { setActiveSession(session.id); setChat(session.messages); setTab('chat'); }
  function confirmDeleteChat() { if (!deleteSessionId) return; setSessions(old => { const next = old.filter(session => session.id !== deleteSessionId); const fallback = next[0] ?? newChatSession(); const final = next.length ? next : [fallback]; if (deleteSessionId === activeSession) { setActiveSession(fallback.id); setChat(fallback.messages); setTab('chat'); } void window.helix.saveChatHistory(final); return final; }); setDeleteSessionId(null); }
  return <main className="app" style={{ '--explorer-width': `${explorerWidth}px`, '--agent-width': `${agentWidth}px` } as React.CSSProperties}>
    <WindowControlsBar onSettings={() => setShowSettings(true)}/>
    <header><div className="brand"><Code2 size={19}/><span>HELIX</span><small>CODE</small></div><button className="open-folder" onClick={pickFolder}><FolderOpen size={16}/> {root ? basename(root) : 'Open Folder…'}</button>{settings?.permissionMode === 'extended' && <div className="danger"><ShieldAlert size={15}/> EXTENDED MODE ACTIVE</div>}<div className="spacer"/><button className="icon-button" title="Settings" onClick={() => setShowSettings(true)}><Settings2 size={18}/></button></header>
    <section className="workspace">
      <aside className="files" tabIndex={0} onKeyDown={event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'){event.preventDefault();void selectAllExplorer();} if(event.key==='Delete'&&explorerSelection.length){event.preventDefault();setPendingExplorerDelete(explorerSelection);}}} onContextMenu={event=>{event.preventDefault();event.stopPropagation();showExplorerMenuAt(event.clientX,event.clientY);}}><div className="pane-head explorer-head"><div className="explorer-location"><span className="explorer-label"><PanelLeft size={15}/> EXPLORER</span><button className="explorer-root-button" title={root ? `Open a different folder (current: ${root})` : 'Open a project folder'} onClick={pickFolder} onContextMenu={event=>{event.preventDefault();event.stopPropagation();if(root)showExplorerRootMenu(event.clientX,event.clientY);}}><FolderOpen size={15}/><span>{root ? basename(root) : 'Open folder'}</span></button></div><div className="explorer-actions"><button className="tiny" title="New file" onClick={() => requestCreate(false)} disabled={!root}><Plus size={15}/></button><button className="tiny" title="New folder" onClick={() => requestCreate(true)} disabled={!root}><Folder size={15}/></button></div></div>{root ? <Tree key={treeRevision} nodes={nodes} openFile={openFile} active={active} selected={explorerSelection} onSelect={selectExplorerItem} onRangeSelect={selectExplorerRange} onMenu={showExplorerMenu}/> : <div className="empty explorer-empty"><FolderOpen size={25}/><strong>No folder open</strong><span>Open a project folder to browse files and use Helix.</span><button onClick={pickFolder}><FolderOpen size={16}/> Open folder</button></div>}</aside>
      <section className="editor"><div className="tabs">{open.map(f => <button key={f.path} className={active === f.path ? 'tab active' : 'tab'} onClick={() => setActive(f.path)}><File size={14}/>{basename(f.path)}{f.dirty ? ' •' : ''}<X size={13} onClick={e => { e.stopPropagation(); setOpen(o => o.filter(x => x.path !== f.path)); if (active === f.path) setActive(null); }}/></button>)}<div className="spacer"/>{current && <><button className="tiny" title="Save" onClick={save}><Save size={16}/></button><button className="tiny delete" title="Delete active file" onClick={remove}><Trash2 size={16}/></button></>}</div>{current ? <Editor height="calc(100vh - 112px)" path={current.path} language={language(current.path)} theme="vs-dark" value={current.content} onChange={value => setOpen(old => old.map(f => f.path === current.path ? { ...f, content: value ?? '', dirty: true } : f))} options={{ minimap: { enabled: false }, fontSize: 14, padding: { top: 14 } }}/> : <div className="welcome"><Bot size={48}/><h1>Your coding workspace</h1><p>Open a folder, inspect code, then ask Helix to help.</p></div>}</section>
      <aside className="agent"><div className="agent-tabs"><button className={tab==='chat'?'selected':''} onClick={() => setTab('chat')}><Bot size={15}/> Agent</button><button className={tab==='history'?'selected':''} onClick={() => { setTab('history'); window.helix.getAudit().then(setAudit); }}><History size={15}/> History</button></div>{tab === 'chat' ? <><div className={running ? 'messages messages-running' : 'messages'}>{chat.length === 0 && <div className="starter"><Bot/><strong>What shall we build?</strong><span>Helix can inspect and edit the open project. It will always ask before commands and deletions.</span></div>}{chat.map(message => <ChatMessage key={message.id} message={message}/>)}{running && <div className="chat-reading-space" aria-hidden="true"/>}</div><ChatComposer draft={draft} running={running} workspaceOpen={!!root} settings={settings} models={chatModels} onDraft={setDraft} onModel={selectChatModel} onWebToggle={toggleWebSearch} onSubmit={submit} onCancel={()=>window.helix.cancelAgent()}/></> : <HistoryList audit={audit}/>}</aside>
    </section>
    <div className={`pane-resizer explorer-resizer ${resizing==='explorer'?'dragging':''}`} title="Drag to resize Explorer" onPointerDown={event=>startResize('explorer',event)}/>
    <div className={`pane-resizer agent-resizer ${resizing==='agent'?'dragging':''}`} title="Drag to resize chat" onPointerDown={event=>startResize('agent',event)}/>
    {tab === 'chat' && <button className="new-chat-corner" title="New chat" onClick={createNewChat}><Plus size={18}/></button>} {tab === 'history' && <ChatSessions sessions={sessions} activeId={activeSession} onNew={createNewChat} onOpen={openChatSession} onDelete={setDeleteSessionId}/>} {fileChanges.length > 0 && <ChangeSummary changes={fileChanges} active={running}/>} {running && <ThinkingDots label={activeTool ?? 'Thinking'}/>} {deleteSessionId && <DeleteChatDialog onCancel={()=>setDeleteSessionId(null)} onConfirm={confirmDeleteChat}/>} 
    {explorerSelection.length>0 && <ExplorerSelectionBar count={explorerSelection.length} onSelectAll={()=>void selectAllExplorer()} onClear={()=>{setExplorerSelection([]);setSelectionAnchor(null);}} onDelete={()=>setPendingExplorerDelete(explorerSelection)}/>} {explorerMenu && <ExplorerContextMenu menu={explorerMenu} hasRoot={!!root} onSelectAll={()=>void selectAllExplorer()} onNewFile={items=>requestCreate(false,explorerParent(items))} onNewFolder={items=>requestCreate(true,explorerParent(items))} onOpen={item=>{setExplorerMenu(null);if(item.type==='file')void openFile(item.path);}} onRename={item=>void renameExplorerItem(item)} onCopy={items=>void copyExplorerPaths(items)} onCloseFolder={()=>void closeFolder()} onDelete={items=>{setExplorerMenu(null);if(items.length)setPendingExplorerDelete(items);}}/>} {pendingExplorerDelete && <MultiDeleteDialog items={topLevelDeleteItems(pendingExplorerDelete)} onCancel={()=>setPendingExplorerDelete(null)} onConfirm={confirmExplorerDelete}/>} {pendingCreate && <CreateItemDialog request={pendingCreate} onCancel={()=>setPendingCreate(null)} onCreate={(name)=>void create(pendingCreate.directory,pendingCreate.parent,name)}/>} {showSettings && settings && <LocalProviderSettingsDialog settings={settings} onClose={() => setShowSettings(false)} onSave={saveSettings}/>} {approval && <Approval request={approval} onApprove={resolveApproval}/>} {showOnboarding && <Onboarding settings={settings} onComplete={(provider,apiKey,model)=>void completeOnboarding(provider,apiKey,model)} onSkip={()=>settings&&void completeOnboarding(settings.provider,settings.apiKey,settings.model)}/>} 
  </main>;
}
function ChatMessage({message}:{message:Chat}) { if (message.role === 'reasoning') return <div className="message reasoning"><details className="reasoning-dropdown"><summary>Thinking</summary><pre>{message.text}</pre></details></div>; return <div className={`message ${message.role}`}>{message.role === 'tool' && <Terminal size={14}/>}<span>{message.text}</span></div>; }
function Onboarding({settings,onComplete,onSkip}:{settings:Settings|null;onComplete:(provider:Provider,apiKey:string,model:string)=>void;onSkip:()=>void}) {
  const [step,setStep]=useState<'welcome'|'provider'|'key'>('welcome'), [provider,setProvider]=useState<Provider | null>(null), [apiKey,setApiKey]=useState(''), [models,setModels]=useState<ModelInfo[]>([]), [model,setModel]=useState(''), [loading,setLoading]=useState(false), [error,setError]=useState('');
  const local=provider==='ollama'||provider==='lmstudio'; const keyUrl=provider==='gemini'?'https://aistudio.google.com/apikey':provider==='openrouter'?'https://openrouter.ai/keys':null;
  function chooseProvider(next:Provider){setProvider(next);setApiKey(settings?.apiKeys[next]??'');setModels([]);setModel('');setError('');}
  async function loadModels(){ if(!provider||(!local&&!apiKey.trim())) return; setLoading(true);setError(''); try { const found=await window.helix.listModels({provider,apiKey,baseUrl:providerDefaults[provider].baseUrl});setModels(found);setModel(old=>old||found[0]?.id||''); } catch(e:any){setModels([]);setError(e.message||'Could not load models. Check your API key and try again.');} finally {setLoading(false);} }
  return <div className="onboarding-screen"><section className="onboarding-content" key={step}>
    {step==='welcome' ? <><p className="onboarding-eyebrow">Welcome to</p><img src={helixLogo} alt="Helix Code"/><button className="onboarding-primary" onClick={()=>setStep('provider')}>Get started <ChevronRight size={17}/></button></> : step==='provider' ? <><p className="onboarding-eyebrow">Set up Helix Code</p><h1>Choose a provider</h1><p className="onboarding-copy">You can change this any time in Settings.</p><div className="onboarding-providers">{onboardingProviders.map(item=><button key={item.provider} className={provider===item.provider?'chosen-provider':''} onClick={()=>chooseProvider(item.provider)}>{item.label}{item.free&&<em>FREE</em>}</button>)}</div><div className="onboarding-actions"><button className="onboarding-back" onClick={()=>setStep('welcome')}><ArrowLeft size={16}/> Back</button><div><button className="onboarding-skip" onClick={onSkip}>Skip</button><button className="onboarding-primary" disabled={!provider} onClick={()=>setStep('key')}>Continue <ChevronRight size={17}/></button></div></div></> : <><p className="onboarding-eyebrow">{onboardingProviders.find(item=>item.provider===provider)?.label}</p><h1>{local?'Load your local models':'Add your API key'}</h1><p className="onboarding-copy">{local?'Helix will read the models available from your local server.':'Your key is saved locally and used only with this provider.'}</p>{keyUrl&&<div className="onboarding-key"><Info size={16}/><span>You can get a free API key for {provider==='gemini'?'Gemini':'OpenRouter'}.</span><button onClick={()=>void window.helix.openExternal(keyUrl)}>Get a free API key</button></div>}{!local&&<label className="onboarding-input">API key<input type="password" value={apiKey} onChange={event=>{setApiKey(event.target.value);setModels([]);setModel('');}} placeholder={provider ? providerDefaults[provider].keyHint : ''}/></label>}<button className="onboarding-load" disabled={loading||(!local&&!apiKey.trim())} onClick={()=>void loadModels()}>{loading?'Loading models…':'Load models'}</button>{models.length>0&&<div className="onboarding-loaded"><CheckCircle2 size={18}/><span><strong>Models loaded</strong><small>{models.length} available from this provider.</small></span></div>}{models.length>0&&<label className="onboarding-input">Model<select value={model} onChange={event=>setModel(event.target.value)}>{models.map(item=><option key={item.id} value={item.id}>{item.label}{item.free?' — FREE':''}</option>)}</select></label>}{error&&<p className="onboarding-error">{error}</p>}<div className="onboarding-actions"><button className="onboarding-back" onClick={()=>setStep('provider')}><ArrowLeft size={16}/> Back</button><button className="onboarding-primary" disabled={!models.length||!model} onClick={()=>provider&&onComplete(provider,apiKey,model)}>Continue <ChevronRight size={17}/></button></div></>}</section></div>;
}
function ChatComposer({draft,running,workspaceOpen,settings,models,onDraft,onModel,onWebToggle,onSubmit,onCancel}:{draft:string;running:boolean;workspaceOpen:boolean;settings:Settings|null;models:ModelInfo[];onDraft:(value:string)=>void;onModel:(model:string)=>void;onWebToggle:()=>void;onSubmit:()=>void;onCancel:()=>void}) { const selected=settings?.model ?? ''; const options=models.some(model=>model.id===selected)?models:[...(selected?[{id:selected,label:selected}]:[]),...models]; const disabled=running||!workspaceOpen; return <div className={workspaceOpen?'composer':'composer composer-disabled'}><div className="composer-controls"><select aria-label="Chat model" value={selected} disabled={!settings||disabled} onChange={event=>onModel(event.target.value)}><option value="">Choose model</option>{options.map(model=><option key={model.id} value={model.id}>{model.label}</option>)}</select><button type="button" className={settings?.webSearchEnabled?'web-toggle active':'web-toggle'} disabled={!settings||disabled} onClick={onWebToggle}>Web {settings?.webSearchEnabled?'on':'off'}</button></div><div className="composer-entry"><textarea value={draft} disabled={disabled} onChange={e=>onDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();onSubmit();}}} placeholder={workspaceOpen?'Ask Helix to work on this project…':'Open a project folder to chat with Helix'}/><button className={running ? 'stop' : 'send'} disabled={!workspaceOpen&&!running} onClick={running?onCancel:onSubmit}>{running?<CircleStop size={18}/>:<Send size={18}/>}</button></div></div>; }
function TreeLegacy({ nodes, openFile, active }: {nodes: FileNode[]; openFile: (p:string)=>void; active:string|null}) { const [expanded,setExpanded]=useState<Record<string,FileNode[]>>({}); const toggle = async (n:FileNode) => { if (expanded[n.path]) return setExpanded(x=>{const y={...x}; delete y[n.path]; return y;}); setExpanded(x=>({...x,[n.path]:[]})); const child=await window.helix.getTree(n.path); setExpanded(x=>({...x,[n.path]:child})); }; return <div className="tree">{nodes.map(n => <div key={n.path}><button className={`node ${active===n.path?'node-active':''}`} onClick={() => n.type==='directory'?toggle(n):openFile(n.path)}>{n.type==='directory'?<ChevronRight size={14} className={expanded[n.path]?'down':''}/>:<span className="indent"/>}{n.type==='directory'?<Folder size={15}/>:<File size={15}/>}<span>{n.name}</span></button>{expanded[n.path] && <div className="children"><Tree nodes={expanded[n.path]} openFile={openFile} active={active}/></div>}</div>)}</div>; }
function LanguageFileIcon({path}:{path:string}) { const ext=path.split('.').pop()?.toLowerCase() ?? ''; const icons:Record<string,[string,string]>={html:['HTML','html'],htm:['HTML','html'],css:['CSS','css'],scss:['SASS','css'],js:['JS','js'],jsx:['JSX','react'],ts:['TS','ts'],tsx:['TSX','react'],py:['PY','python'],json:['{}','json'],yml:['YML','yaml'],yaml:['YML','yaml'],md:['MD','markdown'],svg:['SVG','image'],png:['IMG','image'],jpg:['IMG','image'],jpeg:['IMG','image']}; const icon=icons[ext]; return icon?<span className={`vscode-file-icon ${icon[1]}`}>{icon[0]}</span>:<File size={15}/>; }
function Tree({nodes,openFile,active,selected=[],onSelect=()=>{},onRangeSelect=()=>{},onMenu=()=>{}}:{nodes:FileNode[];openFile:(path:string)=>void;active:string|null;selected?:FileNode[];onSelect?:(item:FileNode,additive:boolean)=>void;onRangeSelect?:(siblings:FileNode[],item:FileNode)=>void;onMenu?:(item:FileNode,x:number,y:number)=>void}) { const [expanded,setExpanded]=useState<Record<string,FileNode[]>>({}); const selectedPaths=new Set(selected.map(item=>item.path)); async function toggle(node:FileNode) { if(expanded[node.path]){setExpanded(old=>{const next={...old};delete next[node.path];return next;});return;} setExpanded(old=>({...old,[node.path]:[]}));const children=await window.helix.getTree(node.path);setExpanded(old=>({...old,[node.path]:children})); } function activate(event:React.MouseEvent<HTMLButtonElement>,node:FileNode){ if(event.shiftKey) onRangeSelect(nodes,node); else onSelect(node,event.ctrlKey||event.metaKey); if(node.type==='directory') void toggle(node); else openFile(node.path); } return <div className="tree">{nodes.map(node=><div key={node.path}><button className={`node ${active===node.path?'node-active':''} ${selectedPaths.has(node.path)?'node-selected':''}`} onClick={event=>activate(event,node)} onContextMenu={event=>{event.preventDefault();event.stopPropagation();onMenu(node,event.clientX,event.clientY);}}>{node.type==='directory'?<ChevronRight size={14} className={expanded[node.path]?'down':''}/>:<span className="indent"/>}{node.type==='directory'?<Folder className="folder-icon" size={15}/>:<LanguageFileIcon path={node.path}/>}<span>{node.name}</span></button>{expanded[node.path]&&<div className="children"><Tree nodes={expanded[node.path]} openFile={openFile} active={active} selected={selected} onSelect={onSelect} onRangeSelect={onRangeSelect} onMenu={onMenu}/></div>}</div>)}</div>; }
function SettingsDialog({settings,onClose,onSave}:{settings:Settings;onClose:()=>void;onSave:(s:Settings)=>void}) { const [s,setS]=useState(settings); const update=(key:keyof Settings,value:any)=>setS(x=>({...x,[key]:value})); return <div className="modal-backdrop"><div className="modal"><h2><KeyRound size={18}/> Provider & permissions</h2><label>Provider<select value={s.provider} onChange={e=>update('provider',e.target.value)}><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="compatible">OpenAI-compatible / local</option></select></label><label>API key<input type="password" value={s.apiKey} onChange={e=>update('apiKey',e.target.value)} placeholder="Stored encrypted by the OS when available"/></label><label>Model<input value={s.model} onChange={e=>update('model',e.target.value)} placeholder="gpt-4.1-mini / claude-sonnet-4…"/></label>{s.provider==='compatible'&&<label>Base URL<input value={s.baseUrl} onChange={e=>update('baseUrl',e.target.value)} placeholder="http://localhost:1234/v1"/></label>}<label className="toggle"><input type="checkbox" checked={s.permissionMode==='extended'} onChange={e=>update('permissionMode',e.target.checked?'extended':'project')}/><span><strong>Extended / Full PC mode</strong><small>Off by default. Outside-project actions and deletions still need approval.</small></span></label><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}>Save settings</button></footer></div></div>; }
const providerDefaults: Record<Provider, { baseUrl: string; modelHint: string; keyHint: string }> = {
  openrouter: { baseUrl: 'https://openrouter.ai/api/v1', modelHint: 'e.g. qwen/qwen3-coder:free', keyHint: 'OpenRouter key (sk-or-...)' }, gemini: { baseUrl: '', modelHint: 'e.g. gemini-2.5-flash', keyHint: 'Google AI Studio API key' }, groq: { baseUrl: 'https://api.groq.com/openai/v1', modelHint: 'Choose a Groq model', keyHint: 'Groq API key' }, openai: { baseUrl: 'https://api.openai.com/v1', modelHint: 'e.g. gpt-4.1-mini', keyHint: 'OpenAI API key' }, anthropic: { baseUrl: '', modelHint: 'e.g. claude-sonnet-4-20250514', keyHint: 'Anthropic API key' }, ollama: { baseUrl: 'http://localhost:11434', modelHint: 'Choose an installed local model', keyHint: 'No key needed for local Ollama' }, lmstudio: { baseUrl: 'http://localhost:1234/v1', modelHint: 'Choose a model loaded in LM Studio', keyHint: 'No key needed for local LM Studio' }, compatible: { baseUrl: '', modelHint: 'Model ID from your provider', keyHint: 'API key, if required' }
};
function ProviderSettingsDialog({settings,onClose,onSave}:{settings:Settings;onClose:()=>void;onSave:(s:Settings)=>void}) {
  const [s,setS]=useState(settings), [models,setModels]=useState<ModelInfo[]>([]), [loading,setLoading]=useState(false), [modelError,setModelError]=useState(''); const update=(key:keyof Settings,value:any)=>setS(x=>({...x,[key]:value})); const preset=providerDefaults[s.provider]; const canLoad=s.provider==='ollama'||!!s.apiKey.trim();
  async function loadModels() { if(!canLoad)return; setLoading(true);setModelError(''); try { const found=await window.helix.listModels({provider:s.provider,apiKey:s.apiKey,baseUrl:s.baseUrl});setModels(found);if(!s.model&&found[0])update('model',found[0].id); } catch(e:any) {setModels([]);setModelError(e.message);} finally {setLoading(false);} }
  function changeProvider(provider:Provider) { const next=providerDefaults[provider];setS(old=>({...old,provider,baseUrl:next.baseUrl,model:''}));setModels([]);setModelError(''); }
  return <div className="modal-backdrop"><div className="modal provider-modal"><h2><KeyRound size={18}/> AI provider & permissions</h2><label>Provider<select value={s.provider} onChange={e=>changeProvider(e.target.value as Provider)}><option value="openrouter">OpenRouter — free & paid models</option><option value="gemini">Google Gemini</option><option value="groq">Groq — fast free tier</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="ollama">Ollama — local & free</option><option value="compatible">Custom OpenAI-compatible</option></select></label><label>API key<input type="password" value={s.apiKey} disabled={s.provider==='ollama'} onChange={e=>update('apiKey',e.target.value)} onBlur={()=>void loadModels()} placeholder={preset.keyHint}/></label>{(s.provider==='compatible'||s.provider==='ollama')&&<label>Base URL<input value={s.baseUrl} onChange={e=>update('baseUrl',e.target.value)} placeholder={preset.baseUrl||'https://provider.example/v1'}/></label>}<div className="model-row"><label>Model<input list="provider-models" value={s.model} onChange={e=>update('model',e.target.value)} placeholder={preset.modelHint}/><datalist id="provider-models">{models.map(m=><option key={m.id} value={m.id}>{m.label}{m.free?' — FREE':''}</option>)}</datalist></label><button className="load-models" disabled={!canLoad||loading} onClick={()=>void loadModels()}>{loading?'Loading...':'Load coding models'}</button></div>{models.length>0&&<div className="model-results">{models.slice(0,12).map(m=><button key={m.id} className={s.model===m.id?'model-choice selected-model':'model-choice'} onClick={()=>update('model',m.id)}><span>{m.label}</span>{m.free&&<em>FREE</em>}</button>)}</div>}{modelError&&<p className="model-error">{modelError}</p>}<p className="provider-note">Models are loaded from the provider after the key is added. OpenRouter results prioritize coding models and label free choices.</p><label className="toggle"><input type="checkbox" checked={s.permissionMode==='extended'} onChange={e=>update('permissionMode',e.target.checked?'extended':'project')}/><span><strong>Extended / Full PC mode</strong><small>Off by default. Outside-project actions and deletions still need approval.</small></span></label><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}>Save settings</button></footer></div></div>;
}
function AutoProviderSettingsDialog({settings,onClose,onSave}:{settings:Settings;onClose:()=>void;onSave:(s:Settings)=>void}) {
  const [s,setS]=useState(settings), [models,setModels]=useState<ModelInfo[]>([]), [loading,setLoading]=useState(false), [modelError,setModelError]=useState(''), [scope,setScope]=useState<'free'|'paid'>('free'), [search,setSearch]=useState(''); const update=(key:keyof Settings,value:any)=>setS(x=>({...x,[key]:value})); const preset=providerDefaults[s.provider]; const canLoad=s.provider==='ollama'||!!s.apiKey.trim();
  async function loadModels() { if(!canLoad)return; setLoading(true);setModelError(''); try { const found=await window.helix.listModels({provider:s.provider,apiKey:s.apiKey,baseUrl:s.baseUrl});setModels(found);if(!s.model&&found[0])update('model',found[0].id); } catch(e:any) {setModels([]);setModelError(e.message);} finally {setLoading(false);} }
  useEffect(()=>{ if(!canLoad){setModels([]);return;} const timer=window.setTimeout(()=>void loadModels(),s.provider==='ollama'?0:600); return()=>window.clearTimeout(timer); },[s.provider,s.apiKey,s.baseUrl]);
  function changeProvider(provider:Provider) { const next=providerDefaults[provider];setS(old=>({...old,provider,baseUrl:next.baseUrl,model:''}));setModels([]);setModelError('');setScope('free');setSearch(''); }
  const freeModels=models.filter(m=>m.free); const visible=models.filter(m=>(s.provider==='openrouter'?scope==='free'?m.free:!m.free:true)&&`${m.label} ${m.id}`.toLowerCase().includes(search.toLowerCase()));
  return <div className="modal-backdrop"><div className="modal provider-modal"><h2><KeyRound size={18}/> AI provider & permissions</h2><label>Provider<select value={s.provider} onChange={e=>changeProvider(e.target.value as Provider)}><option value="openrouter">OpenRouter — free & paid models</option><option value="gemini">Google Gemini</option><option value="groq">Groq — fast free tier</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="ollama">Ollama — local & free</option><option value="compatible">Custom OpenAI-compatible</option></select></label><label>API key<input type="password" value={s.apiKey} disabled={s.provider==='ollama'} onChange={e=>update('apiKey',e.target.value)} placeholder={preset.keyHint}/></label>{(s.provider==='compatible'||s.provider==='ollama')&&<label>Base URL<input value={s.baseUrl} onChange={e=>update('baseUrl',e.target.value)} placeholder={preset.baseUrl||'https://provider.example/v1'}/></label>}<div className="model-row"><label>Selected model<input value={s.model} onChange={e=>update('model',e.target.value)} placeholder={preset.modelHint}/></label><button className="load-models" disabled={!canLoad||loading} onClick={()=>void loadModels()}>{loading?'Loading...':'Refresh models'}</button></div>{models.length>0&&<><div className="model-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search available models..."/>{s.provider==='openrouter'&&<div className="model-tabs"><button className={scope==='free'?'active-scope':''} onClick={()=>setScope('free')}>FREE — curated ({freeModels.length})</button><button className={scope==='paid'?'active-scope':''} onClick={()=>setScope('paid')}>Paid — popular first ({models.length-freeModels.length})</button></div>}</div><div className="model-results full-catalog">{visible.map(m=><button key={m.id} className={s.model===m.id?'model-choice selected-model':'model-choice'} onClick={()=>update('model',m.id)}><span title={m.id}>{m.label}</span>{m.free&&<em>FREE</em>}</button>)}</div>{visible.length===0&&<div className="empty model-empty">No {scope==='free'?'free ':''}models match this search.</div>}</>}{loading&&<p className="provider-note">Loading every model available to this API key...</p>}{modelError&&<p className="model-error">{modelError}</p>}<p className="provider-note">OpenRouter Free is intentionally limited to the five curated models you selected. The Paid list is loaded live and ranks popular coding providers first.</p><label className="toggle"><input type="checkbox" checked={s.permissionMode==='extended'} onChange={e=>update('permissionMode',e.target.checked?'extended':'project')}/><span><strong>Extended / Full PC mode</strong><small>Off by default. Outside-project actions and deletions still need approval.</small></span></label><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}>Save settings</button></footer></div></div>;
}
function SecureProviderSettingsDialog({settings,onClose,onSave}:{settings:Settings;onClose:()=>void;onSave:(s:Settings)=>void}) {
  const [s,setS]=useState(settings), [models,setModels]=useState<ModelInfo[]>([]), [showKey,setShowKey]=useState(false), [loading,setLoading]=useState(false); const preset=providerDefaults[s.provider]; const hasKey=s.provider==='ollama'||!!s.apiKey.trim(); const prefix=s.apiKey?`${s.apiKey.slice(0,7)}${'•'.repeat(Math.min(8,Math.max(3,s.apiKey.length-7)))}`:'No key saved';
  const changeProvider=(provider:Provider)=>setS(old=>{const keys={...old.apiKeys,[old.provider]:old.apiKey};return {...old,apiKeys:keys,provider,apiKey:keys[provider]??'',baseUrl:providerDefaults[provider].baseUrl,model:''};});
  const changeKey=(apiKey:string)=>setS(old=>({...old,apiKey,apiKeys:{...old.apiKeys,[old.provider]:apiKey}}));
  useEffect(()=>{ if(!hasKey){setModels([]);return;} setLoading(true);window.helix.listModels({provider:s.provider,apiKey:s.apiKey,baseUrl:s.baseUrl}).then(items=>{setModels(items);if(!s.model&&items[0])setS(old=>({...old,model:items[0].id}));}).catch(()=>setModels([])).finally(()=>setLoading(false)); },[s.provider,s.apiKey,s.baseUrl]);
  return <div className="modal-backdrop"><div className="modal provider-modal secure-settings"><h2><KeyRound size={18}/> Helix Code settings</h2><label>Provider<select value={s.provider} onChange={e=>changeProvider(e.target.value as Provider)}><option value="openrouter">OpenRouter</option><option value="gemini">Google Gemini</option><option value="groq">Groq</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="ollama">Ollama</option><option value="compatible">Custom OpenAI-compatible</option></select></label><label>API key<div className="key-input"><input type={showKey?'text':'password'} value={s.apiKey} disabled={s.provider==='ollama'} onChange={e=>changeKey(e.target.value)} placeholder={preset.keyHint}/><button type="button" title={showKey?'Hide API key':'Show API key'} onClick={()=>setShowKey(value=>!value)}>{showKey?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><small className="key-prefix">{s.provider==='ollama'?'Local provider — no API key needed':`${prefix} · saved for ${s.provider}`}</small></label>{(s.provider==='compatible'||s.provider==='ollama')&&<label>Base URL<input value={s.baseUrl} onChange={e=>setS(old=>({...old,baseUrl:e.target.value}))} placeholder={preset.baseUrl||'https://provider.example/v1'}/></label>}<label>Model<select value={s.model} onChange={e=>setS(old=>({...old,model:e.target.value}))}><option value="">{loading?'Loading models...':'Choose a model'}</option>{models.map(model=><option key={model.id} value={model.id}>{model.label}{model.free?' — FREE':''}</option>)}</select></label><label className="toggle"><input type="checkbox" checked={s.permissionMode==='extended'} onChange={e=>setS(old=>({...old,permissionMode:e.target.checked?'extended':'project'}))}/><span><strong>Extended / Full PC mode</strong><small>Outside-project actions and deletions still need approval.</small></span></label><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}>Save settings</button></footer></div></div>;
}
function LocalProviderSettingsDialog({settings,onClose,onSave}:{settings:Settings;onClose:()=>void;onSave:(s:Settings)=>void}) {
  const [s,setS]=useState(settings);
  const [models,setModels]=useState<ModelInfo[]>([]);
  const [showKey,setShowKey]=useState(false);
  const [loading,setLoading]=useState(false);
  const [section,setSection]=useState<'providers'|'about'>('providers');
  const preset=providerDefaults[s.provider];
  const isLocal=s.provider==='ollama'||s.provider==='lmstudio';
  const hasKey=isLocal||!!s.apiKey.trim();
  const prefix=s.apiKey?`${s.apiKey.slice(0,7)}${'•'.repeat(Math.min(8,Math.max(3,s.apiKey.length-7)))}`:'No key saved';
  const changeProvider=(provider:Provider)=>setS(old=>{
    const apiKeys={...old.apiKeys,[old.provider]:old.apiKey};
    return {...old,apiKeys,provider,apiKey:apiKeys[provider]??'',baseUrl:providerDefaults[provider].baseUrl,model:''};
  });
  const changeKey=(apiKey:string)=>setS(old=>({...old,apiKey,apiKeys:{...old.apiKeys,[old.provider]:apiKey}}));
  useEffect(()=>{
    if(!hasKey){setModels([]);return;}
    setLoading(true);
    window.helix.listModels({provider:s.provider,apiKey:s.apiKey,baseUrl:s.baseUrl})
      .then(items=>{setModels(items);if(!s.model&&items[0])setS(old=>({...old,model:items[0].id}));})
      .catch(()=>setModels([]))
      .finally(()=>setLoading(false));
  },[s.provider,s.apiKey,s.baseUrl]);
  return <div className="modal-backdrop"><div className="modal provider-modal secure-settings settings-shell">
    <aside className="settings-navigation"><div><KeyRound size={18}/><strong>Settings</strong></div><button className={section==='providers'?'active-settings-section':''} onClick={()=>setSection('providers')}><KeyRound size={16}/> Providers</button><button className={section==='about'?'active-settings-section':''} onClick={()=>setSection('about')}><Info size={16}/> About</button></aside>
    <div className="settings-page">{section==='providers'?<><header className="settings-page-title"><h2>Providers</h2><p>Manage the model provider Helix Code uses.</p></header>
    {(s.provider==='gemini'||s.provider==='openrouter')&&<ProviderKeyBanner provider={s.provider}/>} 
    <label>Provider
      <select value={s.provider} onChange={e=>changeProvider(e.target.value as Provider)}>
        <option value="openrouter">OpenRouter — 𝙁𝙍𝙀𝙀</option><option value="gemini">Google Gemini — 𝙁𝙍𝙀𝙀</option><option value="groq">Groq</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic</option><option value="ollama">Ollama — local — 𝙁𝙍𝙀𝙀</option><option value="lmstudio">LM Studio — local — 𝙁𝙍𝙀𝙀</option><option value="compatible">Custom OpenAI-compatible</option>
      </select>
    </label>
    <label>API key<div className="key-input"><input type={showKey?'text':'password'} value={s.apiKey} disabled={isLocal} onChange={e=>changeKey(e.target.value)} placeholder={preset.keyHint}/><button type="button" title={showKey?'Hide API key':'Show API key'} onClick={()=>setShowKey(value=>!value)}>{showKey?<EyeOff size={16}/>:<Eye size={16}/>}</button></div><small className="key-prefix">{isLocal?'Local provider — no API key needed':`${prefix} · saved for ${s.provider}`}</small></label>
    {(s.provider==='compatible'||isLocal)&&<label>Base URL<input value={s.baseUrl} onChange={e=>setS(old=>({...old,baseUrl:e.target.value}))} placeholder={preset.baseUrl||'https://provider.example/v1'}/></label>}
    <label>Model<select value={s.model} onChange={e=>setS(old=>({...old,model:e.target.value}))}><option value="">{loading?'Loading models...':'Choose a model'}</option>{models.map(model=><option key={model.id} value={model.id}>{model.label}{model.free?' — FREE':''}</option>)}</select></label>
    <label className="toggle"><input type="checkbox" checked={s.webSearchEnabled} onChange={e=>setS(old=>({...old,webSearchEnabled:e.target.checked}))}/><span><strong>Web research</strong><small>Search the public web before every Helix request, then allow focused follow-up searches.</small></span></label>
    <label className="toggle"><input type="checkbox" checked={s.reasoningEnabled} onChange={e=>setS(old=>({...old,reasoningEnabled:e.target.checked}))}/><span><strong>Show model thinking when available</strong><small>Requests provider-supported reasoning or summaries. Some cloud models never expose their private reasoning.</small></span></label>
    <label className="toggle"><input type="checkbox" checked={s.permissionMode==='extended'} onChange={e=>setS(old=>({...old,permissionMode:e.target.checked?'extended':'project'}))}/><span><strong>Extended / Full PC mode</strong><small>Outside-project actions and deletions still need approval.</small></span></label>
    </>:<><header className="settings-page-title"><h2>About</h2><p>Helix Code is a local-first coding workspace that connects to the provider you choose.</p></header><div className="about-card"><img src={helixLogo} alt="Helix Code"/><strong>Helix Code</strong><span>v1.0 BETA</span><small>Made by neonatro</small><div className="about-links"><button type="button" onClick={()=>void window.helix.openExternal('https://github.com/neonatro/helixcode')}><Github size={16}/> neonatro/helixcode</button><button type="button" onClick={()=>void window.helix.openExternal('https://www.instagram.com/neonatro/')}><Instagram size={16}/> @neonatro</button></div><small>Your API keys and chat data stay on this computer.</small></div></>}</div>
    <footer className="settings-footer"><button onClick={onClose}>Cancel</button><button className="primary" onClick={()=>onSave(s)}>Save settings</button></footer>
  </div></div>;
}
function ProviderKeyBanner({provider}:{provider:'gemini'|'openrouter'}) { const gemini=provider==='gemini'; const url=gemini?'https://aistudio.google.com/apikey':'https://openrouter.ai/keys'; return <div className="provider-key-banner"><Info size={15}/><span>You can get a free API key for {gemini?'Gemini':'OpenRouter'}.</span><button type="button" onClick={()=>void window.helix.openExternal(url)}>Get a free API key</button></div>; }
function Approval({request,onApprove}:{request:ToolRequest;onApprove:(ok:boolean,always?:boolean)=>void}) { const [always,setAlways]=useState(false); const cmd=request.tool==='run_command'; return <div className="modal-backdrop"><div className="modal approval"><h2><ShieldAlert size={18}/> Approval required</h2><p>Helix wants to <b>{request.tool.replace('_',' ')}</b>.</p><pre>{JSON.stringify(request.args,null,2)}</pre>{cmd&&<label className="check"><input type="checkbox" checked={always} onChange={e=>setAlways(e.target.checked)}/> Always allow this exact command in this project</label>}<footer><button onClick={()=>onApprove(false)}>Deny</button><button className="primary" onClick={()=>onApprove(true,always)}><Play size={15}/> Approve</button></footer></div></div>; }
function ThinkingDots({label}:{label:string}) { return <div className="thinking-dots" aria-label="Helix is working"><i/><i/><i/><span>{label}</span></div>; }
function WindowControlsBar({onSettings}:{onSettings:()=>void}) { return <div className="window-controls-bar"><div className="window-brand"><img src={helixLogo} alt="Helix Code"/></div><button className="title-settings" title="Open settings" onClick={onSettings}><Cog size={15}/> Settings</button><div className="window-drag"/><div className="window-actions"><button title="Minimize" onClick={()=>window.helix.minimizeWindow()}><Minus size={15}/></button><button title="Maximize" onClick={()=>window.helix.toggleMaximizeWindow()}><Maximize2 size={14}/></button><button className="window-close" title="Close" onClick={()=>window.helix.closeWindow()}><X size={15}/></button></div></div>; }
function ChatSessions({sessions,activeId,onNew,onOpen,onDelete}:{sessions:ChatSession[];activeId:string;onNew:()=>void;onOpen:(session:ChatSession)=>void;onDelete:(id:string)=>void}) { return <aside className="chat-sessions"><header><strong>Chat history</strong><button onClick={onNew}>+ New chat</button></header><div>{sessions.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(session=><div className={session.id===activeId?'session active-session':'session'} key={session.id}><button className="session-open" onClick={()=>onOpen(session)}><strong>{session.title}</strong><small>{new Date(session.updatedAt).toLocaleString()}</small><span>{session.messages.length} messages</span></button><button className="session-delete" title="Delete chat" onClick={()=>onDelete(session.id)}><Trash2 size={15}/></button></div>)}</div></aside>; }
function DeleteChatDialog({onCancel,onConfirm}:{onCancel:()=>void;onConfirm:()=>void}) { return <div className="delete-chat-backdrop"><div className="modal delete-chat-dialog"><h2><Trash2 size={18}/> Delete this chat?</h2><p>This permanently removes the conversation and its saved messages from Helix Code.</p><footer><button onClick={onCancel}>Cancel</button><button className="danger-button" onClick={onConfirm}>Delete chat</button></footer></div></div>; }
function ExplorerSelectionBar({count,onSelectAll,onClear,onDelete}:{count:number;onSelectAll:()=>void;onClear:()=>void;onDelete:()=>void}) { return <div className="explorer-selection-bar"><span>{count} selected</span><button onClick={onSelectAll}>Select all</button><button onClick={onClear}>Clear</button><button className="selection-delete" onClick={onDelete}><Trash2 size={14}/> Delete</button></div>; }
function ExplorerContextMenu({menu,hasRoot,onSelectAll,onNewFile,onNewFolder,onOpen,onRename,onCopy,onCloseFolder,onDelete}:{menu:ExplorerMenu;hasRoot:boolean;onSelectAll:()=>void;onNewFile:(items:FileNode[])=>void;onNewFolder:(items:FileNode[])=>void;onOpen:(item:FileNode)=>void;onRename:(item:FileNode)=>void;onCopy:(items:FileNode[])=>void;onCloseFolder:()=>void;onDelete:(items:FileNode[])=>void}) { const single=menu.items.length===1?menu.items[0]:null; return <div className="explorer-context-menu" style={{left:menu.x,top:menu.y}} onPointerDown={event=>event.stopPropagation()}>{hasRoot&&<><button onClick={()=>onNewFile(menu.items)}><File size={15}/> New file</button><button onClick={()=>onNewFolder(menu.items)}><Folder size={15}/> New folder</button><div className="explorer-context-separator"/></>}{single?.type==='file'&&<button onClick={()=>onOpen(single)}><FolderOpen size={15}/> Open file</button>}{single&&<button onClick={()=>onRename(single)}>Rename</button>}{menu.items.length>0&&<button onClick={()=>onCopy(menu.items)}>Copy {menu.items.length===1?'path':'paths'}</button>}{menu.scope==='root'&&<><div className="explorer-context-separator"/><button onClick={onCloseFolder}>Close folder</button></>}<div className="explorer-context-separator"/><button onClick={onSelectAll}>Select all Explorer</button>{menu.items.length>0&&<button className="explorer-context-delete" onClick={()=>onDelete(menu.items)}><Trash2 size={15}/> Delete selected ({menu.items.length})</button>}</div>; }
function MultiDeleteDialog({items,onCancel,onConfirm}:{items:FileNode[];onCancel:()=>void;onConfirm:()=>void}) { const files=items.filter(item=>item.type==='file').length, folders=items.filter(item=>item.type==='directory').length; const summary=[files?`${files} file${files===1?'':'s'}`:'',folders?`${folders} folder${folders===1?'':'s'}`:''].filter(Boolean).join(' and '); return <div className="delete-chat-backdrop"><div className="modal delete-chat-dialog"><h2><Trash2 size={18}/> Delete selected items?</h2><p>You are about to permanently delete {summary}.</p><p className="multi-delete-note">Any files inside a selected folder will also be deleted.</p><footer><button onClick={onCancel}>Cancel</button><button className="danger-button" onClick={onConfirm}>Delete {items.length} selected</button></footer></div></div>; }
function CreateItemDialog({request,onCancel,onCreate}:{request:CreateRequest;onCancel:()=>void;onCreate:(name:string)=>void}) { const [name,setName]=useState(''); const label=request.directory?'folder':'file'; return <div className="modal-backdrop create-item-backdrop"><form className="modal create-item-dialog" onSubmit={event=>{event.preventDefault();if(name.trim())onCreate(name.trim());}}><h2>{request.directory?<Folder size={18}/>:<File size={18}/>} New {label}</h2><p>Create a new {label} in the selected location.</p><label>Name<input autoFocus value={name} onChange={event=>setName(event.target.value)} placeholder={request.directory?'e.g. components':'e.g. index.html'}/></label><footer><button type="button" onClick={onCancel}>Cancel</button><button className="primary" type="submit" disabled={!name.trim()}>Create {label}</button></footer></form></div>; }
function GeminiChatModelPicker({model,models,hasKey,onChange}:{model:string;models:ModelInfo[];hasKey:boolean;onChange:(model:string)=>void}) { const active=models.some(item=>item.id===model)?model:models[0]?.id||''; return <label className="gemini-chat-model">Gemini model<select value={active} disabled={!hasKey||models.length===0} onChange={e=>onChange(e.target.value)}>{!hasKey?<option>Add Gemini API key in Settings</option>:models.length===0?<option>Loading API models...</option>:models.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</select></label>; }
function ChangeSummary({changes,active}:{changes:FileChange[];active:boolean}) { return <aside className="change-summary"><header><strong>{active?'Files changed so far':'Files changed'}</strong><span>{changes.length} file{changes.length===1?'':'s'}</span></header><div className="change-summary-list">{changes.map(change=><ChangeCard key={change.path} change={change}/>)}</div></aside>; }
function ChangeCard({change}:{change:FileChange}) { const preview=change.preview; const diff=change.action==='deleted'?[['-', 'File deleted.']]:change.action==='modified'&&preview.includes('<<<<<<<')?patchLines(preview):preview.split(/\r?\n/).filter(Boolean).map(line=>['+',line] as const); return <details className="change-card"><summary><File size={14}/><span>{change.action} · {basename(change.path)}</span><small>click to view</small></summary>{preview&&<Editor height="170px" language={language(change.path)} theme="vs-dark" value={preview} options={{readOnly:true,domReadOnly:true,minimap:{enabled:false},fontSize:12,lineNumbers:'off',scrollBeyondLastLine:false}}/>}<pre className="change-diff">{diff.map(([kind,line],i)=><span className={kind==='+'?'add-line':'remove-line'} key={i}>{kind} {line}\n</span>)}</pre></details>; }
function patchLines(patch:string): [string,string][] { const match=patch.match(/^<<<<<<<.*?\n([\s\S]*?)^=======\n([\s\S]*?)^>>>>>>>.*?$/m); if(!match)return patch.split(/\r?\n/).filter(Boolean).map(line=>['+',line]); return [...match[1].split(/\r?\n/).filter(Boolean).map(line=>['-',line] as [string,string]),...match[2].split(/\r?\n/).filter(Boolean).map(line=>['+',line] as [string,string])]; }
function HistoryList({audit}:{audit:AuditEntry[]}) { return <div className="history">{audit.length===0?<div className="empty">Tool activity will appear here.</div>:audit.map(a=><div className="audit" key={a.id}><span className={`badge ${a.approved}`}>{a.approved}</span><strong>{a.tool}</strong><small>{a.target}</small><time>{new Date(a.time).toLocaleString()}</time></div>)}</div>; }
