import { createRoot } from 'react-dom/client';
import { App } from './App';
import './styles.css';
import './provider.css';
import './model-picker.css';
import './thinking.css';
import './chat-scroll.css';
import './change-summary.css';
import './gemini-picker.css';
import './chat-layout.css';
import './language-icons.css';
import './key-settings.css';
import './brand.css';
import './agent-modern.css';
import './chat-controls.css';
import './blood-red.css';
import './theme.css';
import './refined-ui.css';
import './window-controls.css';
import './thinking-position.css';
import './reasoning.css';
import './composer-controls.css';
import './explorer-selection.css';
import './deep-red.css';
import './onboarding.css';
import './onboarding-flow.css';
import './about-links.css';
createRoot(document.getElementById('root')!).render(<App />);
